=== MikeHagerty/asl-java-tools/schemas/SeedScanConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:cfg="config.seedscan.asl"
        targetNamespace="config.seedscan.asl"
        cfg:schemaLocation="https://aslweb.cr.usgs.gov SeedScanConfig.xsd"
        elementFormDefault="qualified"
        attributeFormDefault="qualified">

    <!-- root -->
    <xsd:element name="config"      type="cfg:config_T"/>
    <!-- primary elements -->
    <xsd:element name="lockfile"    type="xsd:string" />
    <xsd:element name="log"         type="cfg:log_T" />
    <xsd:element name="database"    type="cfg:database_T" />
    <xsd:element name="scans"       type="cfg:scans_T" />
    <!-- sub elements -->
    <xsd:element name="scan"        type="cfg:scan_T" />
    <xsd:element name="levels"      type="cfg:log_levels_T" />
    <xsd:element name="level"       type="cfg:log_level_T" />
    <xsd:element name="handlers"    type="cfg:handlers_T" />
    <xsd:element name="handler_level" type="cfg:log_level_T" />
    <xsd:element name="log_console" type="cfg:log_console_T" />
    <xsd:element name="log_file"    type="cfg:log_file_T" />
    <xsd:element name="directory"   type="xsd:string" />
    <xsd:element name="prefix"      type="xsd:string" />
    <xsd:element name="suffix"      type="xsd:string" />
    <xsd:element name="log_db"      type="cfg:log_db_T" />
    <xsd:element name="log_database" type="cfg:database_T" />
    <xsd:element name="uri"         type="xsd:anyURI" />
    <xsd:element name="username"    type="xsd:string" />
    <xsd:element name="password"    type="cfg:password_T" />
    <xsd:element name="encrypted"   type="cfg:encrypted_T" />
    <xsd:element name="plain"       type="xsd:string" />
    <xsd:element name="salt"        type="cfg:salt_T" />
    <xsd:element name="iv"          type="cfg:iv_T" />
    <xsd:element name="ciphertext"  type="xsd:hexBinary" />
    <xsd:element name="hmac"        type="cfg:hmac_T" />
    <xsd:element name="path"        type="xsd:string" />
    <xsd:element name="frequency"   type="cfg:frequency_T" />
    <xsd:element name="start_depth" type="xsd:nonNegativeInteger" />
    <xsd:element name="scan_depth"  type="xsd:integer" />
    <xsd:element name="network_subset"  type="xsd:string" />
    <xsd:element name="station_subset"  type="xsd:string" />
    <xsd:element name="location_subset" type="xsd:string" />
    <xsd:element name="channel_subset"  type="xsd:string" />
    <xsd:element name="operations"  type="cfg:operations_T" />
    <xsd:element name="operation"   type="cfg:operation_T" />
    <!-- scheduling elements -->
    <xsd:element name="year"        type="cfg:year_T" />
    <xsd:element name="years"       type="cfg:year_T" />
    <xsd:element name="month"       type="cfg:month_T" />
    <xsd:element name="months"      type="cfg:month_T" />
    <xsd:element name="week"        type="cfg:week_T" />
    <xsd:element name="weeks"       type="cfg:week_T" />
    <xsd:element name="day"         type="cfg:day_T" />
    <xsd:element name="days"        type="cfg:day_T" />
    <xsd:element name="hour"        type="cfg:hour_T" />
    <xsd:element name="hours"       type="cfg:hour_T" />
    <xsd:element name="minute"      type="cfg:minute_T" />
    <xsd:element name="minutes"     type="cfg:minute_T" />
    <!-- operation elements -->
    <xsd:element name="calibration" type="cfg:opCalibration_T" />

    <xsd:complexType name="config_T">
        <xsd:all>
            <xsd:element ref="cfg:lockfile"     minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:log"          minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:database"     minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:scans"        minOccurs="1" maxOccurs="1"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="log_T">
        <xsd:all>
            <xsd:element ref="cfg:levels"   minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="cfg:handlers" minOccurs="0" maxOccurs="1"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="handlers_T">
        <xsd:all>
            <xsd:element ref="cfg:log_console"  minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="cfg:log_file"     minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="cfg:log_db"       minOccurs="0" maxOccurs="1"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="log_console_T">
        <xsd:all>
            <xsd:element ref="cfg:handler_level" minOccurs="1" maxOccurs="1"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="log_file_T">
        <xsd:all>
            <xsd:element ref="cfg:handler_level" minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:directory"   minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:prefix"      minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:suffix"      minOccurs="1" maxOccurs="1"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="log_db_T">
        <xsd:all>
            <xsd:element ref="cfg:handler_level" minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:log_database"  minOccurs="1" maxOccurs="1"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="database_T">
        <xsd:all>
            <xsd:element ref="cfg:uri" />
            <xsd:element ref="cfg:username" />
            <xsd:element ref="cfg:password" />
            <xsd:element ref="cfg:levels" />
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="password_T">
        <xsd:choice minOccurs="1" maxOccurs="1">
            <xsd:element ref="cfg:encrypted" />
            <xsd:element ref="cfg:plain" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="encrypted_T">
        <xsd:all>
            <xsd:element ref="cfg:salt" />
            <xsd:element ref="cfg:iv" />
            <xsd:element ref="cfg:ciphertext" />
            <xsd:element ref="cfg:hmac" />
        </xsd:all>
    </xsd:complexType>

    <xsd:simpleType name="salt_T">
        <xsd:restriction base="xsd:hexBinary">
            <xsd:length value="8"/> <!-- length in bytes, not ASCII characters -->
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="iv_T">
        <xsd:restriction base="xsd:hexBinary">
            <xsd:length value="16"/> <!-- length in bytes, not ASCII characters -->
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="hmac_T">
        <xsd:restriction base="xsd:hexBinary">
            <xsd:length value="16"/> <!-- length in bytes, not ASCII characters -->
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="operations_T">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element ref="cfg:operation" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="scans_T">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element ref="cfg:scan"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="scan_T">
        <xsd:all>
            <xsd:element ref="cfg:path"             minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:frequency"        minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:start_depth"      minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:scan_depth"       minOccurs="1" maxOccurs="1"/>
            <xsd:element ref="cfg:station_subset"   minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="cfg:network_subset"   minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="cfg:location_subset"  minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="cfg:channel_subset"   minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="cfg:operations"       minOccurs="1" maxOccurs="1"/>
        </xsd:all>
        <xsd:attribute name="id" use="required" type="xsd:nonNegativeInteger" />
    </xsd:complexType>

    <xsd:complexType name="log_levels_T">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="cfg:level" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="log_level_T">
        <xsd:simpleContent>
            <xsd:extension base="cfg:log_level_enum_T">
                <xsd:attribute name="name" use="required" type="xsd:string" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="log_level_enum_T">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="OFF" />
            <xsd:enumeration value="SEVERE" />
            <xsd:enumeration value="WARNING" />
            <xsd:enumeration value="INFO" />
            <xsd:enumeration value="CONFIG" />
            <xsd:enumeration value="FINE" />
            <xsd:enumeration value="FINER" />
            <xsd:enumeration value="FINEST" />
            <xsd:enumeration value="ALL" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="operation_T">
        <xsd:all>
            <xsd:element ref="cfg:calibration" />
        </xsd:all>
    </xsd:complexType>

<!-- Operations -->
    <xsd:complexType name="opCalibration_T">
    </xsd:complexType>

<!-- Frequency of Scans -->
    <xsd:complexType name="frequency_T">
        <xsd:choice minOccurs="0" maxOccurs="1">
            <xsd:element ref="cfg:year" />
            <xsd:element ref="cfg:years" />
            <xsd:element ref="cfg:month" />
            <xsd:element ref="cfg:months" />
            <xsd:element ref="cfg:week" />
            <xsd:element ref="cfg:weeks" />
            <xsd:element ref="cfg:day" />
            <xsd:element ref="cfg:days" />
            <xsd:element ref="cfg:hour" />
            <xsd:element ref="cfg:hours" />
            <xsd:element ref="cfg:minute" />
            <xsd:element ref="cfg:minutes" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="year_T">
        <xsd:choice minOccurs="0" maxOccurs="1">
            <xsd:element ref="cfg:month" />
            <xsd:element ref="cfg:months" />
            <xsd:element ref="cfg:week" />
            <xsd:element ref="cfg:weeks" />
            <xsd:element ref="cfg:day" />
            <xsd:element ref="cfg:days" />
            <xsd:element ref="cfg:hour" />
            <xsd:element ref="cfg:hours" />
            <xsd:element ref="cfg:minute" />
            <xsd:element ref="cfg:minutes" />
        </xsd:choice>
        <xsd:attribute name="value" use="required" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="month_T">
        <xsd:choice minOccurs="0" maxOccurs="1">
            <xsd:element ref="cfg:week" />
            <xsd:element ref="cfg:weeks" />
            <xsd:element ref="cfg:day" />
            <xsd:element ref="cfg:days" />
            <xsd:element ref="cfg:hour" />
            <xsd:element ref="cfg:hours" />
            <xsd:element ref="cfg:minute" />
            <xsd:element ref="cfg:minutes" />
        </xsd:choice>
        <xsd:attribute name="value" use="required" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="week_T">
        <xsd:choice minOccurs="0" maxOccurs="1">
            <xsd:element ref="cfg:day" />
            <xsd:element ref="cfg:days" />
            <xsd:element ref="cfg:hour" />
            <xsd:element ref="cfg:hours" />
            <xsd:element ref="cfg:minute" />
            <xsd:element ref="cfg:minutes" />
        </xsd:choice>
        <xsd:attribute name="value" use="required" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="day_T">
        <xsd:choice minOccurs="0" maxOccurs="1">
            <xsd:element ref="cfg:hour" />
            <xsd:element ref="cfg:hours" />
            <xsd:element ref="cfg:minute" />
            <xsd:element ref="cfg:minutes" />
        </xsd:choice>
        <xsd:attribute name="value" use="required" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="hour_T">
        <xsd:choice minOccurs="0" maxOccurs="1">
            <xsd:element ref="cfg:minute" />
            <xsd:element ref="cfg:minutes" />
        </xsd:choice>
        <xsd:attribute name="value" use="required" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="minute_T">
        <xsd:attribute name="value" use="required" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

</xsd:schema>

=== MikeHagerty/asl-java-tools/config.xml
<?xml version="1.0"?>
<cfg:config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://aslweb.cr.usgs.gov SeedScanConfig.xsd"
            xmlns:cfg="config.seedscan.asl">

    <!--cfg:lockfile>/qcwork/seedscan/seedscan.lock</cfg:lockfile-->
    <cfg:lockfile>seedscan.lock</cfg:lockfile>
 
    <cfg:log>
        <cfg:levels>
            <!-- OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL -->
            <cfg:level cfg:name="">FINEST</cfg:level>
            <cfg:level cfg:name="asl.seedscan">FINEST</cfg:level>
            <cfg:level cfg:name="asl.seedscan.Scanner">INFO</cfg:level>
            <cfg:level cfg:name="asl.seedsplitter">INFO</cfg:level>
        </cfg:levels>

        <cfg:handlers>
            <cfg:log_console>
                <cfg:handler_level>FINEST</cfg:handler_level>
            </cfg:log_console>

            <cfg:log_file>
                <cfg:handler_level>FINE</cfg:handler_level>
                <cfg:directory>logs</cfg:directory>
                <cfg:prefix>seedscan-</cfg:prefix>
                <cfg:suffix>.log</cfg:suffix>
            </cfg:log_file>

            <cfg:log_db>
                <cfg:handler_level>CONFIG</cfg:handler_level>
                <cfg:database>
                    <!--cfg:uri>jdbc:mysql://catbox2.cr.usgs.gov/stations</cfg:uri-->
                    <cfg:uri>jdbc:mysql://136.177.121.210:54321/seedscan</cfg:uri>
                    <cfg:username>seedscan_write</cfg:username>
                    <cfg:password>
                        <cfg:plain>S33dSc@nWr1t3r!</cfg:plain>
                        <!--cfg:encrypted>
                            <cfg:salt>952bf002cc030243</cfg:salt>
                            <cfg:iv>952bf002cc030243952bf002cc030243</cfg:iv>
                            <cfg:ciphertext>2f9cb9a02ee92a392f9cb9a02ee92a39</cfg:ciphertext>
                            <cfg:hmac>952bf002cc030243952bf002cc030243</cfg:hmac>
                        <cfg:encrypted-->
                    </cfg:password>
                </cfg:database>
            </cfg:log_db>
        </cfg:handlers>
    </cfg:log>
  
    <cfg:database>
        <!--cfg:uri>jdbc:mysql://catbox2.cr.usgs.gov/stations</cfg:uri-->
        <cfg:uri>jdbc:mysql://136.177.121.210:54321/seedscan</cfg:uri>
        <cfg:username>seedscan_write</cfg:username>
        <cfg:password>
            <cfg:plain>S33dSc@nWr1t3r!</cfg:plain>
            <!--cfg:encrypted>
                <cfg:salt>952bf002cc030243</cfg:salt>
                <cfg:iv>952bf002cc030243952bf002cc030243</cfg:iv>
                <cfg:ciphertext>2f9cb9a02ee92a392f9cb9a02ee92a39</cfg:ciphertext>
                <cfg:hmac>952bf002cc030243952bf002cc030243</cfg:hmac>
            <cfg:encrypted-->
        </cfg:password>
    </cfg:database>

    <cfg:scans>
        <cfg:scan cfg:id="1">
            <cfg:path>/xs0/seed/${NETWORK}_${STATION}/${YEAR}/${YEAR}_${JDAY}_${NETWORK}_${STATION}</cfg:path>
            <cfg:frequency>
                <cfg:days cfg:value="1">
                    <cfg:hour cfg:value="22"/>
                </cfg:days>
            </cfg:frequency>
            <cfg:start_depth>1</cfg:start_depth>
            <cfg:scan_depth>2</cfg:scan_depth>
            <cfg:operations>
                <cfg:operation>
                    <cfg:calibration/>
                </cfg:operation>
            </cfg:operations>
        </cfg:scan>
     
        <cfg:scan cfg:id="2">
            <cfg:path>/xs0/seed/${NETWORK}_${STATION}/${YEAR}/${YEAR}_${JDAY}_${NETWORK}_${STATION}</cfg:path>
            <cfg:frequency>
                <cfg:years cfg:value="1">
                    <cfg:month cfg:value="12">
                        <cfg:day cfg:value="24">
                            <cfg:hour cfg:value="22">
                                <cfg:minute cfg:value="30"/>
                            </cfg:hour>
                        </cfg:day>
                    </cfg:month>
                </cfg:years>
            </cfg:frequency>
            <cfg:start_depth>1</cfg:start_depth>
            <cfg:scan_depth>366</cfg:scan_depth>
            <cfg:operations>
                <cfg:operation>
                    <cfg:calibration/>
                </cfg:operation>
            </cfg:operations>
        </cfg:scan>
    </cfg:scans>
    
</cfg:config>
